Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "192.168.3.4"

  config.vm.synced_folder "C:/Users/PC/Desktop/devops_homework/devops_html/app", "/var/www/html"

  config.vm.provider "vmware_desktop" do |vm|
    vm.name = "Vagrant-Nginx"
    vm.memory = "1024"
    vm.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Install required packages
    echo "Updating and upgrading packages..."
    sudo apt-get update -y
    sudo apt-get upgrade -y

    # Install Nginx
    echo "Installing Nginx..."
    sudo apt-get install -y nginx
    sudo systemctl enable nginx

    # Check Nginx version
    nginx -v || { echo "Nginx is not installed"; exit 1; }

    # Permission for web directory
    echo "Setting permissions for web directory..."
    sudo chown -R www-data:www-data /var/www/html
    sudo chmod -R 755 /var/www/html

    # Start Nginx
    sudo systemctl start nginx
  SHELL

  config.vm.provision "shell", inline: <<-'SHELL'
    echo "Configuring Nginx site..."
    cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
      try_files \$uri \$uri/ =404;
    }
}
EOL

    # Check config Nginx
    echo "Testing Nginx configuration..."
    sudo nginx -t || { echo "Nginx is not configured correctly"; exit 1; }

    # Restart Nginx
    echo "Restarting Nginx..."
    sudo systemctl restart nginx
    echo "Vagrant provisioning complete!"
  SHELL
end