Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "private_network", ip: "192.168.3.4"

  config.vm.synced_folder "D:/my-work/vagrant_with_nginx/devops_homework/devops_html", "/var/www/html"

  config.vm.provider "vmware_desktop" do |vm|
    vm.name = "Vagrant-Nginx"
    vm.memory = "1024"
    vm.cpus = "2"
  end

  config.vm.provision "shell", path: "provision.sh"
end